### ISSUE TITLE
search deeply about custom tkinter and give us report (how to use it +demo) + how to make multiple pages #please read the note of task

### ISSUE THREAD

**Issue by AsaadAlmughrabi** [Grocer360/Grocery#4]
- how to use it
- know more about library 
- please read documentation of custom tkinter
- write report in detail
- make a simple demo
- due time at 11:30pm
- please attention to due time

**Comment by AbdullahOmar97** [comment]
https://docs.google.com/document/d/1Zr-5LlBsETvDRt7oin5NxrHMM2ekkM-wnaVZE6qJsrk/edit?usp=sharing
